version: '2'
services:
  zookeeper:
    image: hyperledger/fabric-zookeeper

  orderer:
    image: hyperledger/fabric-testenv-orderer
    container_name: orderer
    environment:
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISPROFILE=SampleInsecureKafka
      - CONFIGTX_ORDERER_ORDERERTYPE=kafka
    ports:
      - '7050'
    volumes:
      - /etc/hyperledger/msp:/etc/hyperledger/msp
    depends_on:
      - zookeeper
      - kafka

  kafka:
    image: hyperledger/fabric-kafka
    environment:
      KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE: "false"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
